### ISSUE TITLE
Q: Reserved words and quoting rules for older browsers (IE)?

### ISSUE THREAD

**Issue by Xotic750** [ljharb/eslint-config#21]
I recently ran into a problem with IE8 (ahem), I was using `eslint --fix` and your config and it was unquoting `delete`, which of course causes IE8 sickness.

You have
`"quote-props": [2, "as-needed", { "keywords": true }],`
https://github.com/ljharb/eslint-config/blob/master/.eslintrc#L356
and so the following was left alone, which is what is needed.
```
var obj = {
  'delete': true
};
```

But, then you have
`"dot-notation": [2, { "allowKeywords": true, "allowPattern": "throws" }],`
https://github.com/ljharb/eslint-config/blob/master/.eslintrc#L56
which is not fine as it changes
`if (obj['delete']) {`
to
`if (obj.delete) {`
and is IE8 nauseous.

I changed my rules locally to
`"dot-notation": [2, { "allowKeywords": false }],`
and the sickness went away.

Perhaps you have reason for setting your rules this way?

**Comment by ljharb** [comment]
I'm confused; I have it set to keywords true, and you changed it to keywords true to get it working?

If dot-notation needs a tweak to allow keywords to remain quoted, then that's a bug.

**Comment by Xotic750** [comment]
Apologies, copy/paste error. It should have read that I changed my local rules to
`"dot-notation": [2, { "allowKeywords": false }],`

**Comment by ljharb** [comment]
I don't use autofix; so I don't run into this. It might be a bug in the autofixer tho - "allow keywords" shouldn't force them to change, it should just allow both.

**Comment by Xotic750** [comment]
http://eslint.org/docs/rules/dot-notation

> **Options**
> This rule accepts a single options argument:
> 
> - Set the allowKeywords option to false (default is true) to follow ECMAScript version 3 compatible style, avoiding dot notation for reserved word properties.
> 
> - Set the allowPattern option to a regular expression string to allow bracket notation for property names that match a pattern (by default, no pattern is tested).

I wasn't sure at first either, but reading the document above, it looks like the rule is incorrect?

**Comment by ljharb** [comment]
Sounds good; I'll update the option.
