### ISSUE TITLE
I got the error when i build my project with the latest version 

### ISSUE THREAD

**Issue by manwjc** [ljharb/eslint-config#35]
This dependency was not found:

* has in ./node_modules/_get-intrinsic@1.1.1@get-intrinsic/index.js

To install it, you can run: npm install --save has

Could you help to fix this? Thank you!

**Comment by ljharb** [comment]
I'm not sure what you mean.

First of all, this looks like you're not using npm - pnpm or yarn pnp maybe?

Second, are you using this eslint config directly? In which project?

**Comment by manwjc** [comment]
![image](https://user-images.githubusercontent.com/7971786/165895904-7794894f-5aa8-4ee9-9baa-05bbdede5d93.png)
it warned like this

**Comment by ljharb** [comment]
This is because you're linting node_modules, and you shouldn't be, because that's not your code.

Add `**/node_modules` to `ignorePatterns` in your eslint config.

**Comment by manwjc** [comment]
![image](https://user-images.githubusercontent.com/7971786/165897595-f3ef404b-3a6c-4fa7-b26f-07536cd6a551.png)
I've got this ignore, it still cann't build, but it can build success the last version.

**Comment by ljharb** [comment]
Are you using npm, or something else?

**Comment by manwjc** [comment]
I use cnpm to install

**Comment by ljharb** [comment]
It’s likely that’s doing something nonstandard that’s causing problems, then, if your dep graph is missing dependencies. Be sure get-intrinsic is updated to the latest, of course, but otherwise, try installing with actual npm and see if that fixes it.

Either way, it’s not something related to this project.
